### ISSUE TITLE
Invalid hook call when using in Gutenberg

### ISSUE THREAD

**Issue by robruiz** [phosphor-icons/phosphor-react#33]
Trying to use these in a Gutenberg block (new WordPress editor - which is React essentially). Followed instructions on Github. 
Getting:
react-dom.min.js?ver=17.0.1:9 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.it (react-dom.min.js?ver=17.0.1:9:43163)
    at e.useContext (react.min.js?ver=17.0.1:9:10470)
    at Object.render (IconBase.esm.js:15:31)
    at X (element.min.js?ver=47162ff4492c7ec4956b:9:6463)
    at X (element.min.js?ver=47162ff4492c7ec4956b:9:6459)
    at Z (element.min.js?ver=47162ff4492c7ec4956b:9:7257)
    at B (element.min.js?ver=47162ff4492c7ec4956b:9:6804)
    at X (element.min.js?ver=47162ff4492c7ec4956b:9:6197)
    at xr (blocks.min.js?ver=69022aed79bfd45b3b1d:10:4703)
    at blocks.min.js?ver=69022aed79bfd45b3b1d:10:33666

`import { Horse } from "phosphor-react";
import { useBlockProps } from '@wordpress/block-editor';
export default function Edit() {
	return (
		<div { ...useBlockProps() }>
			{ __(
				'Phosphor Icons – hello from the editor!',
				'phosphor-icons'
			) }
			<Horse />
		</div>
	);
}
`
Error only occurs once I add Horse component
Any ideas here?

**Comment by robruiz** [comment]
For additional context, this only happens when I try to use the component in the save method, but not in the edit method.

**Comment by rektdeckard** [comment]
Sorry @robruiz, I'm not familiar with Gutenberg, but from the error, your problem is likely to be:

1. You might have mismatching versions of React and the renderer (such as React DOM)
2. ~You might be breaking the Rules of Hooks~
3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

I would look into pinning your `react` and `react-dom` versions in your lockfile to make sure only one version is installed and used.
